name: Build Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4.1.6
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0
    - name: Login to Docker Registry
      uses: docker/login-action@v3.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Retrieve version
      id: version
      run: |
        echo "TAG_NAME=$(date +'%s')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - uses: docker/build-push-action@v5.4.0
      name: Build and Push
      id: build-image
      with:
        context: .
        push: true
        file: Dockerfile
        tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ steps.version.outputs.TAG_NAME }},ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
